### ISSUE TITLE
是否可方便改为B/S架构，web-server提供api

### ISSUE THREAD

**Issue by victory460** [zhan3333/converter#1]
项目很棒！目前是桌面客户端的形式，是否可方便改造成 用api的形式提供格式转换服务？

**Comment by zhan3333** [comment]
谢谢。格式转换依赖 ffmpeg，用 web api 来转视频就得考虑上传下载流量带宽费用了。可以考虑 wasm 直接在浏览器提供转换环境，但是 ffmpeg 体积太大，加载到浏览器也太慢了。
